# Stage 1: Build the React application
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the built application with Nginx
FROM nginx:stable-alpine
# Copy the built files from the 'build' stage
COPY --from=build /app/dist /usr/share/nginx/html
# Expose the default Nginx port
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]